apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
  labels:
    app: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image: image-registry.openshift-image-registry.svc:5000/test-pipeline/cicd-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-app
  labels:
    app: cicd-app
    service: cicd-app
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: cicd-app
---
apiVersion: v1
kind: Route
metadata:
  name: cicd-app
spec:
  host: cicd-app-test-pipeline.apps-crc.testing
  path: "/" 
  to:
    kind: Service
    name: cicd-app
